### ISSUE TITLE
REGEX of genome coordinates does not cover chr10

### ISSUE THREAD

**Issue by sreichl** [anthony-aylward/gtracks#1]
this line
https://github.com/anthony-aylward/gtracks/blob/e289021a80c20b2c3a38d72b78cb996ae7ef1350/gtracks/gtracks.py#L78

 should be
```python
COORD_REGEX = re.compile('chr[0-9XY]+:[0-9]+-[0-9]+$')
```

Cheers, S

**Comment by anthony-aylward** [comment]
Thank you for spotting this! I've made the change and updated the package on PyPI.

**Comment by sreichl** [comment]
Great, thanks for the quick fix and the wrapper in general. Very useful!!

**Comment by flyant2** [comment]
for my case:
>>> region ='NC_016845.1:4386244-4392410'
>>> COORD_REGEX = re.compile('[\s\S]+:[0-9]+-[0-9]+$')
>>> print(COORD_REGEX.match(region))
<_sre.SRE_Match object; span=(0, 27), match='NC_016845.1:4386244-4392410'>

**Comment by flyant2** [comment]
1) I changed the following lines on version 1.8.1, it works.  
#COORD_REGEX = re.compile(os.environ.get('GTRACKS_COORD_REGEX',
#                                       '([Cc]hr)?[0-9XY]+:[0-9]+-[0-9]+$'))
COORD_REGEX = re.compile('[\s\S]+:[0-9]+-[0-9]+$')

2) Moreover, No version number provided when using command "gtracks -h" or "gtracks --version".
