### ISSUE TITLE
color not enough 

### ISSUE THREAD

**Issue by flyant2** [anthony-aylward/gtracks#2]
bug line:
       for track, color in zip(tracks, color_palette[:len(tracks)])	
For "len(sns.color_palette().as_hex()) " can only provide  10 colors. 
error when len(tracks) > 10.

So change to :
COLOR_PALETTE = os.environ.get('GTRACKS_COLOR_PALETTE',
    ','.join(sns.color_palette(**'Paired', 16**).as_hex())).split(',')

**Comment by anthony-aylward** [comment]
In version 1.8.1 I have updated `make_tracks_file()` to cycle through colors in the palette, so the the number of tracks is no longer limited by the length of the color palette. Does this solve your issue?

**Comment by flyant2** [comment]
That is good. THANKS!
